# Generated by Django 5.2.6 on 2025-10-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
