# Generated by Django 5.2.6 on 2025-10-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
